Implemented practise 4.1
YaroslavKSE/Professinal-Programming pull request #11
Opened 2024-06-02 11:52 UTC by YaroslavKSE

Implemented builder pattern. Covered the code with unit tests.

2024-06-03 12:59 UTC, vovaskochko requested changes

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/include/IngredientsReader.h
> +#ifndef INGREDIENTSREADER_H
#pragma once may be a better choice for modern compilers

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/include/IngredientsReader.h
> +    std::unordered_map<std::string, Ingredient> readIngredients(const std::string& filename) const;
looks like static methods only in this class - maybe they should be just functions or placed into another class or at least marked as static in this helper class?

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/include/PizzaBuilder.h
> +    Pizza* pizza;
It is better to use unique_ptr and move semantics this will give you an automatic reset on getProduct call
And also in your code I don't observe delete calls inside this class which is a memory leak for the case when something happened and we didn't finish build procedure.

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/include/PizzaBuilder.h
> +    Pizza* getProduct();
[[no_discard]] to avoid the situation when someone mistakenly ignored the result of the function call

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/IngredientsReader.cpp
> +        std::cerr << "Unable to open file: " << filename << std::endl;
std::println(stderr, "Unable to open file: {}", filename);

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/IngredientsReader.cpp
> +        }
std::println

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/Pizza.cpp
> +    for (const auto& ingredient : ingredients) {
maybe std::accumulate can do the trick

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/PizzaBuilder.cpp
> +    this->pizza = new Pizza();
oh no - we are not using raw memory management. Use std::unique and std::make_unique

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/UnitTests/IngredientsReaderTests.cpp
> +    file << content;
Due to RAII and using println it can be rewritten as
```
{
     std::ofstream file(filename);
     std::println(file, content);
}
```

2024-06-03 12:59 UTC, vovaskochko commented on Class/Practise 4.1/src/main.cpp
> +namespace {
Like for named constants. also they can be constexpr which in some cases may impact performance

2024-06-05 06:01 UTC, YaroslavKSE commented on Class/Practise 4.1/include/IngredientsReader.h
> +#ifndef INGREDIENTSREADER_H
Refactored code in [64cf3c3](https://github.com/YaroslavKSE/Professinal-Programming/pull/11/commits/64cf3c3f2d97dd07513dd043c24edd9f95a8e2f4)

2024-06-12 09:50 UTC, vovaskochko approved these changes

2024-06-16 13:12 UTC, merged